### ISSUE TITLE
make编译出错

### ISSUE THREAD

**Issue by NotHaozi** [ics-nju-wl/icspa-public#1]
老师您好，在PA0的时候，执行`make`，会出错，具体如下，请问该怎么解决比较合适？自己更改编译选项是个合适的方法吗？
![image](https://user-images.githubusercontent.com/64006169/167160126-81410183-d305-428f-81a9-dfa53a299885.png)

**Comment by ics-nju-wl** [comment]
可能的解决方案：
1. 改编译选项，去掉 -Werror，当然这个不太好，建议按照下一条解决这个warning
2. 就按照warning的要求，把返回值存一下别忽略，试试看能不能行

**Comment by NotHaozi** [comment]
> 可能的解决方案：
> 
> 1. 改编译选项，去掉 -Werror，当然这个不太好，建议按照下一条解决这个warning
> 2. 就按照warning的要求，把返回值存一下别忽略，试试看能不能行

收到 谢谢！老师周末愉快！

**Comment by ics-nju-wl** [comment]
周末愉快，如果有解决问题，那可以给一下方案然后关闭issue。考虑后续更新一下代码，感谢！

**Comment by NotHaozi** [comment]
老师这样似乎解决不了问题，因为fread解决之后，scanf又会报错。我不得不说明一些情况，我的虚拟机是64位的，操作系统是ubuntu21.04，gcc版本为10

**Comment by NotHaozi** [comment]
老师，存返回值这样似乎解决不了问题，因为fread解决之后，scanf又会警告==报错。

> 我不得不说明一些情况，我的虚拟机是x86_64，操作系统是ubuntu21.04，gcc版本为10。没有按照guide环境要求来，不知道是否与这些有关？
> 另外，我不是南大的学生，非常感谢老师能把那么棒的PA贡献到网上！

**Comment by ics-nju-wl** [comment]
可能和gcc版本有关，我这里测试无法复现该问题（待我更新gcc后再试吧），另外建议用i386虚拟机做，否则你需要修改kernel，testcase和game的编译选项，通过交叉编译将目标架构设置为i386

**Comment by ics-nju-wl** [comment]
目前的quick fix就是去掉 -Werror

**Comment by NotHaozi** [comment]
收到，我还是规规矩矩用i386做吧！
辛苦老师了～

**Comment by NotHaozi** [comment]
RTFM
